### ISSUE TITLE
First day of week

### ISSUE THREAD

**Issue by PepeMty** [backdrop-contrib/fullcalendar_views#13]
In legacy FullCalendar we had the option to config the first dar of the week.

Now I can't find that option. Is this a migration casualty...?

Is there some sort of workaround...?

And thanks for such a great module.

Warm regards from way too sunny México.

José

**Comment by indigoxela** [comment]
Fullcalendar Views NG follows the system "Regional settings" on /admin/config/regional/settings.

The first day setting there also applies to the calendar. :wink:

**Comment by PepeMty** [comment]
@indigoxela 
Thanks so much...!
