### ISSUE TITLE
Layout Problem

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/fullcalendar_views#15]
I am not sure what is going on here but I have a block view display of a calendar.  I put in on a page using a layout.  All works fine until I go edit the layout and add another block.  Instead of appearing in a modal, the blocks appear down at the bottom of the page.

![image](https://user-images.githubusercontent.com/41843284/164717225-5b07b9ff-627f-4116-a520-197751542f3c.png)

This only happens when I have the calendar block in a layout.

Console shows this.  
![image](https://user-images.githubusercontent.com/41843284/164717571-263d295b-e049-4f6b-b179-00e6c9a44897.png)

**Comment by indigoxela** [comment]
> This only happens when I have the calendar block in a layout.

Wow, that looks weird. And following your steps, I can reproduce it. Need to dig a little deeper, what conflicts here.

**Comment by keiserjb** [comment]
Calendar looks great though.  This is just a bit of annoyance to remove the offending block, add others, and then add the calendar again.

**Comment by indigoxela** [comment]
Heck, that's a surprise! The views handler also strikes on the layout admin page. Easy to fix, though.

**Comment by indigoxela** [comment]
Should be fixed in https://github.com/backdrop-contrib/fullcalendar_views/commit/1ed84c98c92e4f695f7843dc5e3a19d51313a6a2 (latest dev). Testing is welcome!

Yes, I also like the look of fullcalendar. :wink: And, no, only being able to add the calendar block last is no option. :laughing:

**Comment by keiserjb** [comment]
> 

This appears to work.

**Comment by indigoxela** [comment]
Great, many thanks for reporting.
