### ISSUE TITLE
Message in views screen: Undefined index: group_rows in FullcalendarViewsStyleCalendar->render() (line 307

### ISSUE THREAD

**Issue by abetomas** [backdrop-contrib/fullcalendar_views#19]
I get this message in views screen.  

> Notice: Undefined index: group_rows in FullcalendarViewsStyleCalendar->render() (line 307 of /Applications/MAMP/htdocs/rc-1a/modules/fullcalendar_views/views/fullcalendar_views_style_calendar.inc).

however, the actual page display of the view works ok and does not show any error
[Repeating-Events.pdf](https://github.com/backdrop-contrib/fullcalendar_views/files/9146597/Repeating-Events.pdf)
s

**Comment by indigoxela** [comment]
I see, you're using the repeating dates field with only the dtstart value.

A PR is available: #20, or if you prefer the diff: https://patch-diff.githubusercontent.com/raw/backdrop-contrib/fullcalendar_views/pull/20.diff

Can you confirm that the PR fixes the notice?

> the actual page display of the view works ok and does not show any error

Yes, this only affects the views preview (I thought, I already fixed that, but obviously that's not the case).

**Comment by abetomas** [comment]
Thanks... I downloaded _fullcalendar_views-19-undef-index-grouprows.zip_ and updated my site.  
**The error messages no longer appear** when I opened the view setup in views.

**Comment by indigoxela** [comment]
@abetomas many thanks for verifying, pull request got merged. :+1:
