### ISSUE TITLE
Additional settings

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/fullcalendar_views#2]
While work is in progress: what additional settings could make sense? Currently there's only the field mapping.

Mainly for the FullCalendar display. The library has oh so many options, so we need to decide what's useful for most people.
Otherwise we end up with a daunting huge settings form. :grinning:

**Comment by Egmund** [comment]
Ups, just started the 'wishlist'

**Comment by indigoxela** [comment]
> Ups, just started the 'wishlist'

No problem. :wink:

**Comment by indigoxela** [comment]
This is what we have now. Some more settings might make sense.

![calendar-display-options](https://user-images.githubusercontent.com/842066/155880924-6c961436-d1f8-4f57-b2d6-b15553c269f8.png)

**Comment by Egmund** [comment]
Ah wonderful. Is the 'zip' updated - or which files should I download/replace? Sorry for my lack of (modern) knowledge.

**Comment by indigoxela** [comment]
No need to excuse.

Yes, GitHub zip files are always up-to-date with the code: [download](https://github.com/backdrop-contrib/fullcalendar_views/archive/refs/heads/1.x-1.x.zip)

**Comment by Egmund** [comment]
Got the week numbers - thank you

**Comment by indigoxela** [comment]
This is what we have now.

Field mapping:
![field-mapping](https://user-images.githubusercontent.com/842066/156189590-e097ff59-ff9b-4dab-9f26-3ff333e55598.png)

Calendar display options:
![calendar-settings](https://user-images.githubusercontent.com/842066/156189640-53187d9e-4669-4007-b2f5-3099e3e2509d.png)

**Comment by Egmund** [comment]
I just updated my code (via cPanel filemanager), cleared the cache, 
tried to run the update.php (no updates to db). I do not get any of the 
new features showing.

What am I missing? Uninstall & reinstall?

Den 01.03.2022 kl. 15.43 skrev indigoxela:

**Comment by indigoxela** [comment]
There's a new dependency: https://backdropcms.org/project/fullcalendar_lib

Install that dependency, then update the view settings (after flushing caches).

**Comment by Egmund** [comment]
Dependency installed & activated - etc.
I must be overlooking something in the 'view'. What do you mean by 'update the view settings'?
Seems I need to uninstall and reinstall.

**Comment by indigoxela** [comment]
> Seems I need to uninstall and reinstall.

Another option is to switch the display type (from Fullcalendar NG to something else, save, then switch back). If you still don't see the additional form fields on the settings form, you'd have to check what went wrong with the upload.
They should be available immediately after flushing caches, though. (Clicking on the format settings of Fullcalendar NG)

**Comment by Egmund** [comment]
Sorry, I made a seeming mistake. I renamed the older version of fullcalendar-views. The site for some reason still used the old renamed version.
Now after deleting it all is as expected. I see the new settings. Sorry for the trouble.

**Comment by Egmund** [comment]
Now that we are at it with color-change options: Could we get that option for the ugly gray buttons in the fc-header-toolbar. No big issue - I can hack the fc css file.

**Comment by indigoxela** [comment]
> Now that we are at it with color-change options: Could we get that option for the ugly gray buttons in the fc-header-toolbar

Could be an option, yes. But I'm not sure if really all people might need this - have to think it over.

> I can hack the fc css file.

You should never, really never, hack any modules or core code or themes, that aren't yours. You will never be able to update again - or it would at least become a pain to update.

Do a subtheme instead. It's not hard, best practice and will make (security-)updates a breeze.

**Comment by Egmund** [comment]
Yes, I ran into that problem several times, so now I usually make an extra css file or make a subtheme.
Hack is quick, dirty and temporary. Css is quick and only need to be 'adressed' in the .info file.

**Comment by indigoxela** [comment]
Why I'm hesitant about the button color settings: that would lead to seven more color input form elements.
Large setting forms is really something I try to avoid.

FTR the original FC settings:
```
  --fc-button-text-color: #fff;
  --fc-button-bg-color: #2C3E50;
  --fc-button-border-color: #2C3E50;
  --fc-button-hover-bg-color: #1e2b37;
  --fc-button-hover-border-color: #1a252f;
  --fc-button-active-bg-color: #1a252f;
  --fc-button-active-border-color: #151e27;
```

**Comment by Egmund** [comment]
Thank you for this - saves me the work. I will make a custom.css
