### ISSUE TITLE
Allow long event titles to wrap

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/fullcalendar_views#26]
**Story**
As a user of a calendar
I want long event titles to wrap
So that users can easily read the full title

**Considerations**
It looks like rows already expand where there are lots of events
It would be good if the full line would wrap so the next line goes under the dot and time rather than just wrapping the title bit which may use up more vertical space.

Just to say, this is not urgent - it is a nice to have, but thought I should add it while I remember.

**Comment by indigoxela** [comment]
@yorkshire-pudding wrapping text is easy to achieve by overriding the FullCalendar CSS - it ships with main.min.css.

The no-wrap and related styles are not provided by this module, but by the library.

Example for an override in your theme:

```
.fc-daygrid-event {
    white-space: normal;
}
```
