### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/fullcalendar_views#3]
Here the first couple of things:
Week numbers would be really handy - used very much here in Denmark.
Week-start choice between Sunday and/or Monday

Can this module btw be used in multi-language settings - Danish and English?

**Comment by indigoxela** [comment]
> Week numbers would be really handy - used very much here in Denmark.

Noted. :wink: 

> Week-start choice between Sunday and/or Monday

It might make sense to just follow system first_day setting (from /admin/config/regional/settings). Then people don't have to set it in two places.

> Can this module btw be used in multi-language settings - Danish and English?

Yes.

**Comment by Egmund** [comment]
Actually - the calendar (table), in month-view, start with monday (which is what I want).

**Comment by indigoxela** [comment]
Closing this in favor of #2
