### ISSUE TITLE
Evaluate new multicalendar view

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/fullcalendar_views#30]
With 6.1 there's a new view available: https://fullcalendar.io/blog/2023/01/multimonth-and-more

See also: https://github.com/backdrop-contrib/fullcalendar_lib/issues/5

Is this something we want/need as a view mode configurable via UI?
Needs some evaluation, as eventually it bloats the admin UI.

**Comment by yorkshire-pudding** [comment]
@indigoxela - yes please!

**Comment by indigoxela** [comment]
@yorkshire-pudding I'm afraid, this has to wait. But describing an actual use-case might help to play with integration later. :wink:

**Comment by yorkshire-pudding** [comment]
No urgency and no pressure @indigoxela, just giving feedback that it would be good. The use case I can see is where events are few and far between in the year  (perhaps a filtered view or an org with not many events) so being able to see the year at a glance is helpful.

PS - I know how annoying it gets when no-one feeds back on suggestions so I try to if I can.

**Comment by Egmund** [comment]
I would also like the possibility of a 'year-view'. We have bi-annual events at one site.
But definitely no rush - we have been working fine without it - with a few more posts/mails.

**Comment by indigoxela** [comment]
@Egmund I'm afraid, per default the FullCalendar lib doesn't provide a year view (all months combined in one stack), so I'm not sure, if that's feasible with reasonable effort with that lib. But you'd probably want to explore the possibilities of regular views displays (table with grouping, for example).

**Comment by indigoxela** [comment]
Hm, I took a quick look and have bad news. Unless I'm missing something, to provide code depending on the FullCalendar.MultiMonth plugin, I'd have to create a custom build (either with yarn or npm).

That's not something that will happen any time soon, as it really complicates the lib updates in fullcalendar_lib. Sorry folks.

**Comment by yorkshire-pudding** [comment]
No problem. Thanks for checking out
