### ISSUE TITLE
Tooltip for only the first 5 items

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/fullcalendar_views#35]
When tooltips are shown, only the first 5 items of the calendar show it. The next ones don't show a tooltip.

**Comment by indigoxela** [comment]
@robertgarrigos many thanks for reporting. However, I need **steps to reproduce**. As long as I haven't, I wouldn't know, how to help you.

**Comment by robertgarrigos** [comment]
Create a fullcalendar view with nodes across a couple of months. When switching from one month to the other, the tooltips disappear. I noticed that I only have this problem with bootstrap themes (both 3.x and 5.x) but not with basis.

**Comment by robertgarrigos** [comment]
This is already reported here: #16
