### ISSUE TITLE
Error with PHP 8.3

### ISSUE THREAD

**Issue by Wylbur** [backdrop-contrib/fullcalendar_views#39]
The following error is generated when using PHP 8.3 with the module.
`Deprecated function: file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated in fullcalendar_get_version() (line 385 of /home/sapaseniors/sapsbd/docroot/modules/fullcalendar/fullcalendar.module).`

This is also documented with the Drupal 7 module:
https://www.drupal.org/project/fullcalendar/issues/3363828

**Comment by Wylbur** [comment]
Oops. wrong module!  Sorry!

**Comment by indigoxela** [comment]
> Oops. wrong module! Sorry!

Maybe you should consider switching, then? :wink:
