### ISSUE TITLE
Empty space under table head and under bottom line

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/fullcalendar_views#4]
There is a margin or padding under the table head and at the bottom of last (bottom) line in table in all three views, month, week, day, which means the inner vertical lines of the table have gaps and top dates/times are a little low.
I have not been able to locate (yet) where this comes from.
It does not exist in the 'old' fullcalendar, nor in Drupal 7 calendar.

**Comment by indigoxela** [comment]
> There is a margin or padding under the table head and at the bottom of last (bottom) line

Can you provide a screenshot where you highlight the padding/margin? I'm not sure what you refer to.

**Comment by Egmund** [comment]
YesSir,
First: Goind down through the classes and divs:
There is a 8px padding in
<tr role="presentation" class="fc-scrollgrid-section fc-scrollgrid-section-header  fc-scrollgrid-section-sticky">
Is this maybe where the 'trouble' starts?

**Comment by Egmund** [comment]
![billede](https://user-images.githubusercontent.com/37831689/155881398-a235f99a-9232-41a0-973e-1bbb4a8174d4.png)
Hope the pix got here. The vertical lines between the days does not go al the way up. There is a gap of about 8px. The first - leftmost outer line is fine. The numbers also have more space above them than lower rows

**Comment by Egmund** [comment]
![billede](https://user-images.githubusercontent.com/37831689/155881489-458706b9-6e54-4a14-a51f-2e7b8ea18543.png)

**Comment by Egmund** [comment]
The bottom line also have lines w. gap but at the bottom:
![billede](https://user-images.githubusercontent.com/37831689/155881531-2e6331d3-4e5b-4e75-9df1-030d8c99fd05.png)

**Comment by indigoxela** [comment]
I see, that's the Basis stylesheet fiddling in here. To override that, you only need to remove the margin.

```
.fullcalendar-view table {
  margin: 0;
}
```

**Comment by Egmund** [comment]
I am using Axioma, but probably. I will try this.

**Comment by Egmund** [comment]
Yes, that is it. Problem solved.

**Comment by indigoxela** [comment]
Right, other themes might also define a margin, that's not uncommon. That makes me think that this module should ship with a stylesheet to fix that...

**Comment by indigoxela** [comment]
> ... makes me think that this module should ship with a stylesheet to fix that

Stylesheet added. @Egmund many thanks for the hint. :+1:
