### ISSUE TITLE
Allow listMonth display type?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/fullcalendar_views#40]
It looks like I can probably extend settings on my own via https://github.com/backdrop-contrib/fullcalendar_views/pull/29/files at this point, but I wonder if it would be considered to add `listMonth` as a display type? In my local testing it seems everything needed is already included, except adding it as an option/selection here in the FullCalendar settings on the View:

![CleanShot 2024-07-02 at 08 18 09@2x](https://github.com/backdrop-contrib/fullcalendar_views/assets/871421/ca7e6bc9-0ece-4967-8ac4-583a0e4f9595)

**Comment by indigoxela** [comment]
Hey @laryn,
what is listMonth view? :wink: 

There's List View and MultiMonth Grid (with some variants) - which one are you after? This one: https://fullcalendar.io/docs/multimonth-grid?

Yes, I belief, you can already do it on your own by extending.

May I know your use-case?

**Comment by laryn** [comment]
@indigoxela 

An internal accessibility review on a site suggested that adding a list format would be beneficial from an a11y perspective, given how the regular view ends up cutting off titles, etc.

From https://fullcalendar.io/docs/list-view: 
> There are 4 preset list views: listDay, listWeek, listMonth, and listYear. 

Demo:
 - https://fullcalendar.io/docs/list-view-demo

**Comment by indigoxela** [comment]
Ah, now I get it. :smile:

If A11Y's important, any table style view's problematic, that's true.
I didn't add that list mode initially, as views (the module) provides such displays out-of-the-box. But providing an easy and accessible toggle might be worth adding it...

**Comment by laryn** [comment]
Yes, I agree. If you're only going to have a list format you probably want to build that without FullCalendar but if you want the ability to flip between them it's handy to have that toggle there.

**Comment by laryn** [comment]
@indigoxela -- should I submit a PR?

**Comment by indigoxela** [comment]
> should I submit a PR?

@laryn not necessary, I already added one. It would be great if you test it.

**Comment by laryn** [comment]
@indigoxela Looks great -- tested and RTBC. Thanks!
