### ISSUE TITLE
Allow additional sources, provide a views plugin for that

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/fullcalendar_views#6]
Oh dear, a concept problem:

With the current approach (field mapping), only one date (field) type is possible per view. That seems like an unnecessary limitation.
The same calendar should be able to show Date fields, recurring dates...

Needs a little rewrite, though.

**Comment by Egmund** [comment]
Yes, I was wondering about that.
But 'only' using recurring-date field seems fine since that can be used for single events apparently

**Comment by indigoxela** [comment]
Thinking this over... allowing to add mixed date field types to the same view makes the code awkwardly complicated.

FullCalendar knows tricks, though - it can parse additional json feeds. Will look into that options, when time permits.

**Comment by indigoxela** [comment]
It's now possible to add additional json feeds (as urls), for instance created with views_json.

That's not really super-easy if not familiar with FC, but possible.

If time permits, I'd like to look into a possibility for a "feed-like" views plugin provided by this module or a submodule, to attach stuff in a more convenient way. But first of all let's see if people find fullcalendar_views useful, anyway. :wink:
