### ISSUE TITLE
Consider browser locale, add option in view settings form

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/fullcalendar_views#8]
Currently the label language (month, day, date format...) follows the page language, but it may make sense to consider the browser language setting instead.

**Comment by Egmund** [comment]
I would think it should follow the page language. It would be odd to have several languages on one page.

**Comment by indigoxela** [comment]
> I would think it should follow the page language.

That's why it should be a setting (and default off). :wink:

There's a use-case, though, for the browser language: monolingual sites that wish to present the calendar in a locale, the international visitors understand. Like month names, day names... but most of all date/time formats.
